/**
 * `opencode-channels setup <platform>` — Interactive setup wizard.
 *
 * Currently supports: slack
 *
 * Steps:
 *   1. Prompt for credentials (bot token, signing secret)
 *   2. Validate credentials via the platform API
 *   3. (Optional) Auto-configure the Slack app manifest via the Manifest API
 *   4. Write credentials to .env / config DB
 */

import { Command } from 'commander';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { createInterface } from 'node:readline';

// ─── Readline helper ────────────────────────────────────────────────────────

function ask(question: string, hidden = false): Promise<string> {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      rl.close();
      resolve(answer.trim());
    });
  });
}

// ─── .env file helpers ──────────────────────────────────────────────────────

function readEnvFile(path: string): Map<string, string> {
  const map = new Map<string, string>();
  if (!existsSync(path)) return map;
  const content = readFileSync(path, 'utf-8');
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    map.set(trimmed.slice(0, eqIdx), trimmed.slice(eqIdx + 1));
  }
  return map;
}

function writeEnvFile(path: string, entries: Map<string, string>): void {
  const lines: string[] = [];

  // Preserve existing comments and structure if file exists
  if (existsSync(path)) {
    const content = readFileSync(path, 'utf-8');
    const handled = new Set<string>();

    for (const line of content.split('\n')) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) {
        lines.push(line);
        continue;
      }
      const eqIdx = trimmed.indexOf('=');
      if (eqIdx === -1) {
        lines.push(line);
        continue;
      }
      const key = trimmed.slice(0, eqIdx);
      if (entries.has(key)) {
        lines.push(`${key}=${entries.get(key)}`);
        handled.add(key);
      } else {
        lines.push(line);
      }
    }

    // Append new keys not already in the file
    for (const [key, value] of entries) {
      if (!handled.has(key)) {
        lines.push(`${key}=${value}`);
      }
    }
  } else {
    // New file
    lines.push('# opencode-channels configuration');
    lines.push('# Generated by: opencode-channels setup');
    lines.push('');
    for (const [key, value] of entries) {
      lines.push(`${key}=${value}`);
    }
  }

  writeFileSync(path, lines.join('\n') + '\n');
}

// ─── Slack setup ────────────────────────────────────────────────────────────

async function setupSlack(options: { envFile: string; autoManifest: boolean }) {
  const envPath = resolve(process.cwd(), options.envFile);
  const existing = readEnvFile(envPath);

  console.log('');
  console.log('Slack Setup');
  console.log('===========');
  console.log('');

  // 1. Collect credentials
  const botToken =
    existing.get('SLACK_BOT_TOKEN') ||
    (await ask('Slack Bot Token (xoxb-...): '));

  if (!botToken.startsWith('xoxb-')) {
    console.error('ERROR: Bot token should start with "xoxb-"');
    process.exit(1);
  }

  const signingSecret =
    existing.get('SLACK_SIGNING_SECRET') ||
    (await ask('Slack Signing Secret: '));

  if (!signingSecret) {
    console.error('ERROR: Signing secret is required');
    process.exit(1);
  }

  // 2. Validate credentials
  console.log('');
  console.log('Validating credentials...');

  const { SlackAdapter } = await import('@opencode-channels/slack');
  const adapter = new SlackAdapter({
    getConfigByTeamId: () => undefined,
    getClient: () => {
      throw new Error('not needed for validation');
    },
  });

  const validation = await adapter.validateCredentials({
    botToken,
    signingSecret,
  });

  if (!validation.valid) {
    console.error(`ERROR: Credentials invalid — ${validation.error}`);
    process.exit(1);
  }

  console.log('Credentials are valid!');

  // 3. Save to .env
  const envEntries = new Map(existing);
  envEntries.set('SLACK_BOT_TOKEN', botToken);
  envEntries.set('SLACK_SIGNING_SECRET', signingSecret);

  // 4. Optional manifest auto-config
  if (options.autoManifest) {
    console.log('');
    console.log('Manifest Auto-Configuration');
    console.log('---------------------------');

    const appId =
      existing.get('SLACK_APP_ID') || (await ask('Slack App ID (e.g. A0AGVEKGHFG): '));

    const refreshToken =
      existing.get('SLACK_CONFIG_REFRESH_TOKEN') ||
      (await ask('Configuration Refresh Token (xoxe-...): '));

    if (!appId || !refreshToken) {
      console.log('Skipping manifest auto-config (missing App ID or refresh token).');
      console.log(
        'Get a configuration token at: https://api.slack.com/authentication/config-tokens',
      );
    } else {
      envEntries.set('SLACK_APP_ID', appId);
      envEntries.set('SLACK_CONFIG_REFRESH_TOKEN', refreshToken);

      // Detect ngrok
      const { detectNgrokUrl } = await import('@opencode-channels/slack');
      const ngrokUrl = await detectNgrokUrl();

      if (!ngrokUrl) {
        console.log('ngrok not detected. Start ngrok first: ngrok http 3456');
        console.log('Manifest auto-config will run when you start the server.');
      } else {
        console.log(`ngrok detected: ${ngrokUrl}`);
        console.log('Configuring Slack app manifest...');

        const { setupSlackApp } = await import('@opencode-channels/slack');
        const result = await setupSlackApp({
          appId,
          refreshToken,
          baseUrl: ngrokUrl,
        });

        // Always persist new refresh token
        if (result.newRefreshToken) {
          envEntries.set('SLACK_CONFIG_REFRESH_TOKEN', result.newRefreshToken);
        }

        if (result.ok) {
          console.log('Manifest updated successfully!');
          console.log(`  Events:        ${ngrokUrl}/slack/events`);
          console.log(`  Interactivity: ${ngrokUrl}/slack/interactivity`);
          console.log(`  Commands:      ${ngrokUrl}/slack/commands`);
        } else {
          console.error(`Manifest update failed: ${result.error}`);
          console.log('You can configure URLs manually in the Slack app dashboard.');
        }
      }
    }
  }

  writeEnvFile(envPath, envEntries);
  console.log('');
  console.log(`Configuration saved to ${envPath}`);
  console.log('');
  console.log('Next steps:');
  console.log('  1. Start ngrok:           ngrok http 3456');
  console.log('  2. Start the server:      opencode-channels start');
  console.log('  3. @mention the bot in Slack!');
  console.log('');
}

// ─── Command definition ─────────────────────────────────────────────────────

export const setupCommand = new Command('setup')
  .description('Interactive setup wizard for a platform adapter')
  .argument('<platform>', 'Platform to set up (slack, telegram, discord)')
  .option('--env-file <path>', 'Path to .env file', '.env')
  .option('--no-auto-manifest', 'Skip automatic Slack manifest configuration')
  .action(async (platform: string, options: { envFile: string; autoManifest: boolean }) => {
    switch (platform.toLowerCase()) {
      case 'slack':
        await setupSlack(options);
        break;
      case 'telegram':
        console.log('Telegram setup is not yet implemented.');
        console.log('Set TELEGRAM_BOT_TOKEN in your .env file manually.');
        break;
      case 'discord':
        console.log('Discord setup is not yet implemented.');
        console.log('Set DISCORD_APPLICATION_ID, DISCORD_BOT_TOKEN, and DISCORD_PUBLIC_KEY in your .env file.');
        break;
      default:
        console.error(`Unknown platform: ${platform}`);
        console.error('Supported platforms: slack, telegram, discord');
        process.exit(1);
    }
  });
